---

- name: R1sof Agent Installation
  hosts: all
   become: true 
   become_method: sudo
   user: centos 
   
   task: 
  - name: create repo
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
     copy: 
      src: r1soft.repo
      dest: /etc/yum.repos.d 
   
      
  - name: install agent
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
     package:
       name: serverbackup-enterprice-agent
       state: installed 
    notify: AGENT_RESTART       
      
  - name: Stop iptables 
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
    service:
      name: iptables
      state: restarted 
      enabled: false
      
  - name: Get Key
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
    shell: "r1soft-setup -- get-key http://52.56.105.64/"   

  handlers: 
    name: AGENT_RESTART 
    service: 
       name: cdp-agent
       state: restarted
       enabled: true 

